export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST"
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE"

export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST"
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS"
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE"

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST"
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE"

export const SEARCH_ITEM_REQUEST = "SEARCH_ITEM_REQUEST"
export const SEARCH_ITEM_SUCCESS = "SEARCH_ITEM_SUCCESS"
export const SEARCH_ITEM_FAILURE = "SEARCH_ITEM_FAILURE"