export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST"
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS"
export const ADD_STORE_FAILURE = "ADD_STORE_FAILURE"

export const GET_STORES_REQUEST = "GET_STORES_REQUEST"
export const GET_STORES_SUCCESS = "GET_STORES_SUCCESS"
export const GET_STORES_FAILURE = "GET_STORES_FAILURE"